### ISSUE TITLE
mission map request

### ISSUE THREAD

**Issue by gtbii** [kotyy/enlightenokc-jarvis#2]
Google Fusion Table is used to create a Google Map with local mission. 

Looking to add custom command to Jarvis to have him pull map image or list of inputs from the map based on given location {zip code, address, etc}

Viewable map is found at: 
https://www.google.com/fusiontables/embedviz?q=select+col8+from+1fcYuKkOVrEW-1BbndpfbkFBShjEQHL7e1cT6A1cm&viz=MAP&h=false&lat=35.46773035208889&lng=-97.50915550000002&t=1&z=13&l=col8&y=2&tmplt=2&hml=TWO_COL_LAT_LNG

Fusion Tablet is found at:
https://www.google.com/fusiontables/DataSource?docid=1fcYuKkOVrEW-1BbndpfbkFBShjEQHL7e1cT6A1cm

**Comment by kotyy** [comment]
fixed by b7817b0deb9e6909a2c5c94a1e923c8af310aecf
