### ISSUE TITLE
missions fusion table map link changed

### ISSUE THREAD

**Issue by gtbii** [kotyy/enlightenokc-jarvis#3]
There was an issue with the Fusion table used to produce this map and a new one had to be created. Please change the map jarvis pulls from to https://www.google.com/fusiontables/embedviz?q=select+col8+from+1IdtxAhxrcFFafLiPDLhoQsonk8LDxuMZzqoKiUIl&viz=MAP&h=false&lat=35.73254312233255&lng=-97.19625014147948&t=1&z=9&l=col8&y=2&tmplt=2&hml=ONE_COL_LAT_LNG

Thank you

**Comment by kotyy** [comment]
Meant to say I updated the link this weekend.
